### PR TITLE
Update of Readme

### PR DESCRIPTION
**Pull request by raphaelsteixeira**
Update of Readme

### CODE REVIEW

**Comment by raphaelsteixeira** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by raphaelsteixeira** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by raphaelsteixeira** [comment]
recheck

**Review by NazariGamer — APPROVED** [review]
No comments. Approved.

**Comment by NazariGamer** [comment]
Merge

**Pull request merged**
